### ISSUE TITLE
[Build] Using CUDA 11.4

### ISSUE THREAD

**Issue by robertschade** [RRZE-HPC/likwid#423]
**Which version do you want to build?**
commit f3a4aa447f51922308a0efc10baa3f1bd4d85069 with CUDA 11.4. (It builds with CUDA 11.3)

**Which architecture do you want to build for?**
- [x] x86_64
- [ ] ARMv8
- [ ] POWER9
- [x] Nvidia GPUs
- [ ] x86 (32 bit)
- [ ] ARMv7
- [ ] POWER8

**To Reproduce**
- Changes to `config.mk` (you may leave out `PREFIX` changes)
`NVIDIA_INTERFACE = true#NO SPACE`
- Changes to build configurations `make/include_<COMPILER>.mk`
- Any other changes
`export CUDA_HOME=/usr/local/cuda-11.4/`

**Output log**
Error output of `make distclean && make`
```
===>  COMPILE  GCC/nvmon.o
In file included from ./src/nvmon.c:75:
./src/includes/nvmon_perfworks.h:178:55: error: unknown type name ‘NVPA_RawMetricsConfigOptions’
  178 | DECLARE_NVPWFUNC(NVPA_RawMetricsConfig_Create, (const NVPA_RawMetricsConfigOptions*, NVPA_RawMetricsConfig**));
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/includes/nvmon_perfworks.h:167:69: note: in definition of macro ‘DECLARE_NVPWFUNC’
  167 | #define DECLARE_NVPWFUNC(fname, fsig) NVPA_Status NVPWAPIWEAK fname fsig; NVPA_Status( *fname##Ptr ) fsig;
      |                                                                     ^~~~
./src/includes/nvmon_perfworks.h:178:55: error: unknown type name ‘NVPA_RawMetricsConfigOptions’
  178 | DECLARE_NVPWFUNC(NVPA_RawMetricsConfig_Create, (const NVPA_RawMetricsConfigOptions*, NVPA_RawMetricsConfig**));
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/includes/nvmon_perfworks.h:167:102: note: in definition of macro ‘DECLARE_NVPWFUNC’
  167 | #define DECLARE_NVPWFUNC(fname, fsig) NVPA_Status NVPWAPIWEAK fname fsig; NVPA_Status( *fname##Ptr ) fsig;
      |                                                                                                      ^~~~
./src/includes/nvmon_perfworks.h: In function ‘nvmon_perfworks_createConfigImage’:
./src/includes/nvmon_perfworks.h:1003:5: error: unknown type name ‘NVPA_RawMetricsConfigOptions’; did you mean ‘NVPA_RawMetricsConfig’?
 1003 |     NVPA_RawMetricsConfigOptions metricsConfigOptions = { NVPA_RAW_METRICS_CONFIG_OPTIONS_STRUCT_SIZE };
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |     NVPA_RawMetricsConfig
./src/includes/nvmon_perfworks.h:1003:59: error: ‘NVPA_RAW_METRICS_CONFIG_OPTIONS_STRUCT_SIZE’ undeclared (first use in this function); did you mean ‘NVPA_RAW_METRIC_REQUEST_STRUCT_SIZE’?
 1003 |     NVPA_RawMetricsConfigOptions metricsConfigOptions = { NVPA_RAW_METRICS_CONFIG_OPTIONS_STRUCT_SIZE };
      |                                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                           NVPA_RAW_METRIC_REQUEST_STRUCT_SIZE
./src/includes/nvmon_perfworks.h:1003:59: note: each undeclared identifier is reported only once for each function it appears in
./src/includes/nvmon_perfworks.h:1004:25: error: request for member ‘activityKind’ in something not a structure or union
 1004 |     metricsConfigOptions.activityKind = NVPA_ACTIVITY_KIND_PROFILER;
      |                         ^
./src/includes/nvmon_perfworks.h:1005:25: error: request for member ‘pChipName’ in something not a structure or union
 1005 |     metricsConfigOptions.pChipName = chip;
      |                         ^
make: *** [Makefile:301: GCC/nvmon.o] Fehler 1
```

**Comment by TomTheBear** [comment]
Hi,
I saw the same error like 15 minutes ago. I'm currently setting up CI to hopefully catch those errors in the future.
It seems Nvidia breaks their own API in a minor release because previous 11.x versions work fine. I'll take a look.

Best,
Thomas
